apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: vlsingle-name
spec:
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
  vpa:
    updatePolicy:
      updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: '*'
