apiVersion: operator.victoriametrics.com/v1
kind: VTSingle
metadata:
  name: vtsingle-name
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  vpa:
    updatePolicy:
      updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: '*'
  networkPolicy: {}
