kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vlinsert-to-vlstorage-packet-corrupt
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vlinsert
  mode: all
  action: corrupt
  duration: 7m
  corrupt:
    corrupt: '25'
    correlation: '0'
  direction: to
  target:
    selector:
      namespaces:
        - vm
      labelSelectors:
        app.kubernetes.io/name: vlstorage
    mode: all
