kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vlinsert-response-abort
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vlinsert
  mode: all
  target: Response
  abort: true
  port: 9481
  path: '/insert*'
  duration: 7m
