kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: vlselect-response-abort
spec:
  selector:
    namespaces:
      - vm
    labelSelectors:
      app.kubernetes.io/name: vlselect
  mode: all
  target: Response
  abort: true
  port: 9471
  path: /select/*
  duration: 7m
