apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-netpol
spec:
  remoteWrite:
    - url: http://localhost:8480/insert/0/prometheus/api/v1/write
  networkPolicy: {}
