apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-hpa
spec:
  remoteWrite:
    - url: http://localhost:8480/insert/0/prometheus/api/v1/write
  hpa:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
